const images = import.meta.glob('../assets/portfolioImages/*.{png,jpg,jpeg,svg}', { eager: true }); // Dynamically import all (image) files in the portfolioimages folder:

const prefix = '../assets/portfolioImages/';
export const slides = [
   
  
          { src: images[`${prefix}01.jpg`].default,
            title: 'London Thames North Bank, UK',
            description: 'Panorama over byen, set fra London City Hall',
          },
          { src: images[`${prefix}02.jpg`].default,
            title: 'Tokyo Downtown, Japan',
            description: 'Akabanebashi Crossing fodgængerfeltet set fra Tokyo Tower',
          },
          { src: images[`${prefix}03.jpg`].default,
            title: 'Sydney Opera House & Harbour Bridge, Australia',
            description: 'Solnedgang over byens vartegn',
          },
          { src: images[`${prefix}04.jpg`].default,
            title: 'UFC championships, Birmingham, UK',
            description: 'UFC 89: Keith Jardine (tv) vs. Brandon Vera (th)',
          },
          { src: images[`${prefix}05.jpg`].default,
            title: 'The Warehouse Project nightclub, Manchester, UK', 
            description: 'DJ John Digweed hylder publikum'
          },
          { src: images[`${prefix}06.jpg`].default,
            title: 'Pokémon Championships, London, UK',
            description: 'Øjeblikket TontonBatteuse vandt EUIC i PoGo',
          },
          { src: images[`${prefix}07.jpg`].default,
            title: '1972 Lotus Europa Twin Cam, Brighton, UK',
            description: 'Lavprofil sportsvogn, som blev produceret i 1971-1975.',
          },
          { src: images[`${prefix}08.jpg`].default,
            title: 'Koenigsegg CC850, LEGO HQ, Denmark',
            description: 'Tophastighed på 450 km/t, lanceret i 2023, og her kørt af Tom Cruise.',
          },
          { src: images[`${prefix}09.jpg`].default,
            title: '1982 Merlin Roadster Plus Two, Ruddington, UK',
            description: 'Klassisk sportsvogn (prod. 1982-1985) ved gammel benzinstander.',
          },

          

          /*{ src: images['../assets/portfolioImages/'+'0'+3+'.jpg'].default },*/
        
  /*
  'London Thames North Bank, UK',
    'Tokyo Downtown, Japan',
    'Sydney Opera House & Harbour Bridge, Australia',
    //'Sheikh Zayed Road, Dubai, United Arab Emirates',
    'UFC championships, Birmingham, UK',
    'DJ John Digweed at The Warehouse Project nightclub, Manchester, UK', 
    //'Big Ben, London, UK',
    //'St. Peter\'s Square, Vatican City, Rome, Italy',
    //'The Hemicycle, EU Parliament, Strasbourg, France',
    //'Legoland Resort, Billund, Denmark',
    'European Intl. Championships, Pokemon, London, UK',
    //'Der Reichstag, Platz der Republik, Berlin, Germany',
    '1972 Lotus Europa Twin Cam, Brighton, UK',
    'Koenigsegg CC850 driven by Tom Cruise, LEGO HQ, Denmark',
    '1982 Merlin Roadster Plus Two, Ruddington, UK',
    //'Optical laser assembly',
    //'Spiral plant',
    //'Swiss pocket clock, Zürich, Switzerland',
    'Wedding',
    'Portrait, child',
    'Portrait, adult',
    'Griffon over coastline, Benalmádena, Spain',//Eurasian Griffon Vulture
    'Emus, Wilsons Promontory, Victoria, Australia',
    'Red Deer, Wollaton Park, Nottingham, UK',
    'Aerial view from El Teide volcano, Tenerife, Canary Islands, Spain',
    'Whitsunday Islands Beach, Queensland Waters, Australia',
    'Rub\' al Khali Desert / The \'Empty Quarter\', Arabia',
    'Street food',
    'Drinks reception',
    'Chocolate cake and ice cream dessert',
    /*'Laboratory samples',
    'Biochemist, UK',
    'Computer chip',
    'Burj Khalifa, Dubai, UAE - World\'s Tallest Building',
    'Petronas Towers, Kuala Lumpur, Malaysia',
    'St. Peter\'s Square, Rome / Vatican City, Italy',
    'Egyptian statues, art museum, Denmark',*/
  ];