const iArc = import.meta.glob('../assets/portfolioImages/01/*.{png,jpg,jpeg,svg}', { eager: true }); // Dynamically import all (image) files in the portfolioimages folder:
const iEve = import.meta.glob('../assets/portfolioImages/02/*.{png,jpg,jpeg,svg}', { eager: true }); // Dynamically import all (image) files in the portfolioimages folder:
const iWed = import.meta.glob('../assets/portfolioImages/03/*.{png,jpg,jpeg,svg}', { eager: true }); // Dynamically import all (image) files in the portfolioimages folder:
const iPor = import.meta.glob('../assets/portfolioImages/04/*.{png,jpg,jpeg,svg}', { eager: true }); // Dynamically import all (image) files in the portfolioimages folder:
const iPro = import.meta.glob('../assets/portfolioImages/05/*.{png,jpg,jpeg,svg}', { eager: true }); // Dynamically import all (image) files in the portfolioimages folder:
const iMar = import.meta.glob('../assets/portfolioImages/06/*.{png,jpg,jpeg,svg}', { eager: true }); // Dynamically import all (image) files in the portfolioimages folder:
const iSpo = import.meta.glob('../assets/portfolioImages/07/*.{png,jpg,jpeg,svg}', { eager: true }); // Dynamically import all (image) files in the portfolioimages folder:
const iWil = import.meta.glob('../assets/portfolioImages/08/*.{png,jpg,jpeg,svg}', { eager: true }); // Dynamically import all (image) files in the portfolioimages folder:
const iLan = import.meta.glob('../assets/portfolioImages/09/*.{png,jpg,jpeg,svg}', { eager: true }); // Dynamically import all (image) files in the portfolioimages folder:
const iMisc = import.meta.glob('../assets/portfolioImages/10/*.{png,jpg,jpeg,svg}', { eager: true }); // Dynamically import all (image) files in the portfolioimages folder:

const prefix = '../assets/portfolioImages/';
const w = 1400;
const h = 932;
export const slides = [

// load in images in categories: 01 Location / cityscapes, 02 Event, 03 Wedding, 04 Portrait, 05 Product, 06 Marketing (/Branding), 07 Sport, 08 Wildlife, 09 Landscape (/Nature incl. astro), 10 Cuisine (Food/drink)
  
          { src: iArc[`${prefix}01/011.jpg`].default,
            title: 'London Thames North Bank, UK',
            description: 'Panorama over byen, set fra London City Hall',
            cat: '1',
            //width: 700, height: 466 
          },
          { src: iArc[`${prefix}01/02.jpg`].default,
          title: 'Tokyo Downtown, Japan',
          description: 'Akabanebashi Crossing fodgængerfeltet set fra Tokyo Tower',
          cat: '1',
          width: 1400, height: 932 
          },
          { src: iArc[`${prefix}01/031.jpg`].default,
            title: 'Sydney Opera House & Harbour Bridge, Australia',
            description: 'Solnedgang over byens vartegn',
            cat: '1',
          },
          { src: iArc[`${prefix}01/04.jpg`].default,
            title: 'Burj Khalifa, Dubai, UAE',
            description: 'Verdens højeste bygning - på 829m!',
            cat: '1',
          },
          { src: iArc[`${prefix}01/10.jpg`].default,
            title: 'The Frame, Dubai, UAE',
            description: 'Tæt på den 150m høje "Billedrammen"',
            cat: '1',
          },
          { src: iEve[`${prefix}02/31.jpg`].default,
            title: 'UFC championships, Birmingham, UK',
            description: 'UFC 89: Keith Jardine (tv) vs. Brandon Vera (th)',
            cat: '2',
          },
          { src: iEve[`${prefix}02/32.jpg`].default,
            title: 'The Warehouse Project nightclub, Manchester, UK', 
            description: 'DJ John Digweed hylder publikum',
            cat: '2',
          },
          { src: iEve[`${prefix}02/33.jpg`].default,
            title: 'Pokémon Championships, London, UK',
            description: 'Øjeblikket TontonBatteuse vandt EUIC i PoGo',
            cat: '2',
          },
          { src: iWed[`${prefix}03/61.jpg`].default,
            title: 'Umbrella',
            description: 'Sammen under paraplyen',
            cat: '3',
          },
          { src: iWed[`${prefix}03/62.jpg`].default,
            title: 'Bouquet',
            description: 'Stilhed ved solnedgang',
            cat: '3',
          },
          { src: iWed[`${prefix}03/63.jpg`].default,
            title: 'Confetti',
            description: 'Strøet med konfetti',
            cat: '3',
          },
          { src: iWed[`${prefix}03/64.jpg`].default,
            title: 'Girl with hairband',
            description: 'Pige med hårbøjle',
            cat: '3',
          },
          { src: iWed[`${prefix}03/65.jpg`].default,
            title: 'Ring on finger',
            description: 'Ring på fingeren',
            cat: '3',
          },
          { src: iWed[`${prefix}03/66.jpg`].default,
            title: 'Make-up',
            description: 'Sminkning',
            cat: '3',
          },
          { src: iWed[`${prefix}03/67.jpg`].default,
            title: 'Two hearts',
            description: 'Hjertepar',
            cat: '3',
          },
          { src: iWed[`${prefix}03/68.jpg`].default,
            title: 'Wedding layer cake',
            description: 'Bryllupslagkage',
            cat: '3',
          },
          { src: iPor[`${prefix}04/91.jpg`].default,
            title: 'Portrait, child',
            description: 'Klar til en dukkert',
            cat: '4',
          },
          { src: iPor[`${prefix}04/92.jpg`].default,
            title: 'Portrait, adult',
            description: 'Stilfuldt påklædt',
            cat: '4',
          },
          { src: iPro[`${prefix}05/121.jpg`].default,
            title: 'Nikon 70-200mm f2.8E FL VR',
            description: 'Zoomobjektiv',
            cat: '5',
          },
          { src: iPro[`${prefix}05/122.jpg`].default,
            title: 'Computer chip',
            description: 'Forstørret kig på elektronisk kredsløb',
            cat: '5',
          },
          { src: iMar[`${prefix}06/151.jpg`].default,
            title: 'Petronas Towers view from Hotel Room',
            description: 'Værelse med udsigt',
            cat: '6',
          },
          { src: iMar[`${prefix}06/152.jpg`].default,
            title: 'Car dealership',
            description: 'Røde Ferrarier',
            cat: '6',
          },
          { src: iSpo[`${prefix}07/181.jpg`].default,
            title: 'Martial arts stand',
            description: 'Grafik af kampsportsudøver',
            cat: '7',
          },
          { src: iSpo[`${prefix}07/182.jpg`].default,
            title: 'Pool player, Ningbo, China',
            description: 'Pool',
            cat: '7',
          },
          { src: iSpo[`${prefix}07/183.jpg`].default,
            title: 'Swimmer',
            description: 'Svømmer',
            cat: '7',
          },
          { src: iSpo[`${prefix}07/184.jpg`].default,
            title: 'Kayaker, National Watersports Centre, England',
            description: 'Kajakvending',
            cat: '7',
          },
          { src: iSpo[`${prefix}07/208.jpg`].default,
            title: '1972 Lotus Europa Twin Cam, Brighton, UK',
            description: 'Lavprofil sportsvogn, som blev produceret fra 1971-1975',
            cat: '7',
          },
          { src: iSpo[`${prefix}07/209.jpg`].default,
            title: 'Koenigsegg CC850, LEGO HQ, Denmark',
            description: 'Tophastighed på 450 km/t, lanceret i 2023, her kørt af Tom Cruise',
            cat: '7',
          },
          { src: iSpo[`${prefix}07/210.jpg`].default,
            title: '1982 Merlin Roadster Plus Two, Ruddington, UK',
            description: 'Klassisk sportsvogn (prod. 1982-1985) ved gammel benzinstander',
            cat: '7',
          },
          { src: iWil[`${prefix}08/211.jpg`].default,
            title: 'Griffon over coastline, Benalmádena, Spain',
            description: 'Højt at svæve...',
            cat: '8',
          },
          { src: iWil[`${prefix}08/212.jpg`].default,
            title: 'Emus, Wilsons Promontory, Victoria, Australia',
            cat: '8',
            description: 'Målfoto',
          },
          { src: iWil[`${prefix}08/213.jpg`].default,
            title: 'Red Deer, Wollaton Park, Nottingham, UK',
            description: 'Kronhjorte på vagt',
            cat: '8',
          },
          { src: iWil[`${prefix}08/214.jpg`].default,
            title: 'Horse at Lady Bay stables, Nottingham, UK',
            description: 'Hest',
            cat: '8',
          },
          { src: iLan[`${prefix}09/241.jpg`].default,
            title: 'El Teide volcano, Tenerife, Canary Islands, Spain',
            description: 'Områdeudsigt højt oppefra',
            cat: '9',
          },
          { src: iLan[`${prefix}09/242.jpg`].default,
            title: 'Whitsunday Islands Beach, Queensland Waters, Australia',
            description: 'Whitehaven strands kridthvide sand',
            cat: '9',
          },
          { src: iLan[`${prefix}09/243.jpg`].default,
            title: 'Rub\' al Khali Desert / The \'Empty Quarter\', Arabia',
            description: 'Solnedgang i ørkenen',
            cat: '9',
          },
          { src: iMisc[`${prefix}10/271.jpg`].default,
            title: 'Street food',
            description: 'Madservice på gadeplan',
            cat: '10',
          },
          { src: iMisc[`${prefix}10/272.jpg`].default,
            title: 'Drinks reception',
            description: 'Champagne og juice',
            cat: '10',
          },
          { src: iMisc[`${prefix}10/273.jpg`].default,
            title: 'Chocolate cake and ice cream dessert',
            description: 'Søde fristelser',
            cat: '10',
          },
          { src: iMisc[`${prefix}10/274.jpg`].default,
            title: 'Blueberries',
            description: 'Blåbær',
            cat: '10',
          },
          { src: iMisc[`${prefix}10/275.jpg`].default,
            title: 'Full Moon',
            description: 'Fuldmåne',
            cat: '10',
          },
]
        
  /*
    'Sheikh Zayed Road, Dubai, United Arab Emirates',
    'Big Ben, London, UK',
    'St. Peter\'s Square, Vatican City, Rome, Italy',
    'The Hemicycle, EU Parliament, Strasbourg, France',
    'Legoland Resort, Billund, Denmark',
    'Der Reichstag, Platz der Republik, Berlin, Germany',
    'Optical laser assembly',
    'Spiral plant',
    'Swiss pocket clock, Zürich, Switzerland',
    'Laboratory samples',
    'Biochemist, UK',
    'Burj Khalifa, Dubai, UAE - World\'s Tallest Building',
    'Petronas Towers, Kuala Lumpur, Malaysia',
    'St. Peter\'s Square, Rome / Vatican City, Italy',
    'Egyptian statues, art museum, Denmark',
    */